### PR TITLE
Don't animate avatars (specify png)

### PR DESCRIPTION
**Pull request by bobbybee**
See comment for why this is a good idea and shouldn't regress anyone (https://xkcd.com/1172/)

### CODE REVIEW

**Comment by EionRobb** [comment]
There's already a setting in Pidgin for this
image

**Comment by bobbybee** [comment]
I see..

**Comment by EionRobb** [comment]
ah, well the hell not :)

**Comment by bobbybee** [comment]
:P

I feel like animated avatars were a Mistake (TM) anyway, but maybe
that's just me :p

**Pull request merged**
