### PR TITLE
add scalable icon (from official site)

### PR DESCRIPTION
**Pull request by kompowiec**
very small change. Also thank you for this great plugin ;)

### CODE REVIEW

**Comment by EionRobb** [comment]
When you say "official site" what do you mean?

What license is the file provided under?

**Comment by kompowiec** [comment]
2.3 Trademark License and Branding. Subject to the terms of this Agreement, Discord grants you a limited, non-exclusive, revocable, non-transferable license to display the Discord trademark solely for the purpose of attributing the source of the API or SDK and indicating that you used the API or SDK in creating your Applications. In doing so, you shall adhere to Discord’s brand guidelines, currently located at https://discordapp.com/branding. In addition, all use of the SDK must be in compliance with Discord’s in-game brand guidelines. All use by you of the Discord trademark (including any goodwill associated therewith) shall inure to the benefit of Discord. At no time during or after the term of this Agreement shall you challenge or assist others to challenge the Discord trademark or the registration thereof by Discord, nor shall you attempt to register the Discord trademark or brand identifiers (including domain names) that are confusingly similar in any way (including but not limited to, sound, appearance and spelling) to the Discord trademark. You shall include in your Applications, website and other relevant locations a disclaimer stating that your Applications, website or any services is or are not endorsed or created by Discord.
https://discordapp.com/developers/docs/legal

**Comment by EionRobb** [comment]
Unfortunately the restrictions on that sound like it wouldn't be GPL-compliant :(

**Comment by bobbybee** [comment]
> Unfortunately the restrictions on that sound like it wouldn't be GPL-compliant :(

(And it probably forbids us from being distributed in Debian/Fedora/etc,
at least not in main)

**Comment by EionRobb** [comment]
Sorry, going to have to close this PR, unless you can find a recreation of the logo (ideally with the tango colour scheme, if possible), that has an open/libre license that's GPL compatible (such as a Creative Commons license)

**Comment by kompowiec** [comment]
https://pixabay.com/en/icons-social-networks-software-3414428/
maybe this?

**Pull request closed without merging**
