### PR TITLE
Include Gentoo build instructions

### LINKED ISSUE #29: Gentoo Ebuild
Great job with this plugin, I just found it and it works wonders, and I want to contribute in the only way I can.
I'm a gentoo user and I wrote a simple Ebuild that can be tested by other gentoo users.

To use the ebuild:
1. Copy it to "/usr/local/portage/x11-plugins/purple-discord" (creating the folders if necessary)
2. Run `ebuild purple-discord-9999.ebuild manifest`
3. If eix is installed, run `eix-update; eix-diff`

Now the plugin should be able to be installed with `emerge purple-discord`.

If this works well, I could request the Gentoo team to include the ebuild in portage.

Hope it helps a bit.
[ebuild.zip](https://github.com/EionRobb/purple-discord/files/994369/ebuild.zip)

### PR DESCRIPTION
**Pull request by bobbybee**
This closes #29

### CODE REVIEW

**Comment by Penaz91** [comment]
I suggest adding a `cd` command to the ebuild directory before doing the `ebuild manifest` command, the rest looks perfect.

**Comment by EionRobb** [comment]
Not entirely sure if it's the correct thing to do to include an rebuild in the repo?

**Comment by Penaz91** [comment]
I see it as a distribution-specific makefile, in some way, i don't see why not.
If you prefer I can make a repository in my account to hold the ebuild in.

**Comment by bobbybee** [comment]
(to both of you) better?

**Comment by Penaz91** [comment]
Looks good for me.

**Comment by EionRobb** [comment]
Good enough :)

**Pull request merged**
