### PR TITLE
Improve channel mentions

### PR DESCRIPTION
**Pull request by Eloston**
Improve channel mentions by including the guild name and using `discord_normalise_room_name`. If the guild name isn't available for some reason, just have `#` followed by the channel name.

This also fixes a crash when the client receives a channel mention with an unknown channel id.

### CODE REVIEW

**Comment by EionRobb** [comment]
Nice :) Thanks :+1:

**Comment by mimi89999** [comment]
So how do I mention?

**Comment by Eloston** [comment]
@mimi89999 There's no "user-friendly" way of instantiating any mention right now. The only way right now is to use [Discord's extensions to the Markdown format](https://discordapp.com/developers/docs/resources/channel#message-formatting) when composing your message.

**Comment by mimi89999** [comment]
So I need to right click on user, info, get the ID and type `<@ID>`? Not quite intuitive...

**Comment by EionRobb** [comment]
@mimi89999 it's still a work in progress. See https://github.com/EionRobb/purple-discord/issues/25

**Pull request merged**
