### PR TITLE
Wrapped error to support libpurple3 build

### PR DESCRIPTION
**Pull request by Fank**
And it works

image

### CODE REVIEW

**Comment by Fank** [comment]
@EionRobb better?

**Comment by EionRobb** [comment]
Apologies, I didn't explain myself very well :) 

I mean, to not use a wrapper but instead to use the purple_notify_error() function in the code and then add a fallback for purple2

The intention is to target the code to purple3 primarily, with compat code, and only ever so slight amounts of purple3 compat code where its completely unavoidable

**Comment by Fank** [comment]
I know what you mean but i don't know how to overwrite a function call with a preprocessor macro.
The only solution i know is to use a wrapper macro.

**Comment by Fank** [comment]
I think i may found a solution, but could not test it, only have a pidgin 3 enviroment.

**Comment by Fank** [comment]
@EionRobb i think this is a good solution, if it works :D

**Comment by EionRobb** [comment]
I was just looking at what the 5th parameter is supposed to be in purple3 for `purple_notify_error()` and it looks like it should be the callback from `purple_request_cpar_from_connection(pc)`, but we already expand that out to `#define purple_request_cpar_from_connection(a)  purple_connection_get_account(a), NULL, NULL` for the `purple_request_input()` calls. 

So the line should be
`purple_notify_error(da, _("Bad channel type"), _("Cannot join a voice channel as text"), "", purple_request_cpar_from_connection(da->pc));`
and then that would expand to the equivalent of
`purple_notify_error(da, _("Bad channel type"), _("Cannot join a voice channel as text"), "", da->account, NULL, NULL);` so that certainly complicates the `purple_notify_error()` call a lot more.  Hummm.

What a can of worms you have opened 😄

**Comment by Fank** [comment]
Di you want to take a look in it, you are more familiar with it, than me?
Or should i try to resolve it?

**Comment by EionRobb** [comment]
Lets get this merged so that it'll work on purple3, and I'll tidy up for purple2 :)

Thanks for your work, and thanks for talking it through

**Comment by Fank** [comment]
@EionRobb I send you a mail yesterday, i would be thankful if you could answer it. :D

**Pull request merged**
