### PR TITLE
Preserve order of guild groups

### LINKED ISSUE #163: Pidgin groups keep moving to the top
Whenever the account is enabled and reconnected, or connected for the first time, the default groups created for each server (guild?) keep moving to the top of the buddy list, even after I've moved them around.

### PR DESCRIPTION
**Pull request by tpenguinltg**
Fixes #163

### CODE REVIEW

**Comment by bobbybee** [comment]
Nicely done.

**Comment by EionRobb** [comment]
This isn't purple3 compatible. Structs are opaque and functions should be users to get the previous group instead

**Comment by bobbybee** [comment]
....oops?

**Comment by EionRobb** [comment]
The cause of the problem is that `purple_blist_add_group` shouldn't be called if the group is already in the blist, otherwise the group will get moved around

**Comment by tpenguinltg** [comment]
So if the call to `purple_blist_find_group` earlier in the function returns something, can it be assumed that it's already in the blist?

**Comment by EionRobb** [comment]
@tpenguinltg yes, that's correct. If the add-group function was moved inside the "if not exists" check then it would only add if needed :)

**Pull request merged**
