### PR TITLE
Remove hg specific code from Makefile

### PR DESCRIPTION
**Pull request by bobbybee**
#64, #80, ... it confuses people for functionality which I don't think is used by anyone but Eion 🙄

### CODE REVIEW

**Comment by EionRobb** [comment]
How about using `git` with an `hg` fallback, so that we have the best of both worlds?

**Comment by bobbybee** [comment]
I'm not convinced this is functionality we need in the Makefile anyway..

**Comment by EionRobb** [comment]
It's there to know what version of the plugin was built, in the absence of real version numbers

**Comment by xvitaly** [comment]
@EionRobb Please merge this pull request.

**Comment by EionRobb** [comment]
Without a git fallback (or a git+hg fallback) we don't have a reasonable way of knowing what dev version of the plugin people are using

**Pull request closed without merging**
