### PR TITLE
Channel categories

### LINKED ISSUE #175: Handling channel categories
Channel categories are shown as a chat in the buddy list, just like channels.
This means I can open a channel category in pidgin and send a message to it, but it does nothing on the server side, so the message just vanishes.

Either remove the categories from the buddy list or turn them into groups on the buddy list.

### PR DESCRIPTION
**Pull request by bobbybee**
Closes #175

### CODE REVIEW

**Comment by bobbybee** [comment]
I also added support for exposing these categories in the Room List view.

**Comment by bobbybee** [comment]
Added some more stuff while I was in the room list implementation so now hidden channels are properly hidden in the room list (which should save some embarassment - most people don't realize hidden channels still leak metadata..)

**Comment by bobbybee** [comment]
Threw in some more roomlist improvements while I was working on that set of code. It should be much happier now -- a shame Pidgin doesn't make much use of it, but alas.

**Comment by EionRobb** [comment]
Classy as always :)

tyvm

**Pull request merged**
